{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exporter.name" . }}
  labels: {{- include "exporter.labels" . | nindent 4 }}
stringData:
  {{- if .Values.bifrostAdminUsername }}
  BIFROST_ADMIN_USERNAME: {{ .Values.bifrostAdminUsername | quote }}
  BIFROST_ADMIN_PASSWORD: {{ .Values.bifrostAdminPassword | quote }}
  {{- end }}
  DOIT_API_KEY: {{ required "set doitApiKey or existingSecret" .Values.doitApiKey | quote }}
{{- end }}
